v160

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -66,21 +66,29 @@ jobs:
           FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
         shell: pwsh
 
-      - name: Verify FIREBASE_CREDENTIALS
-        run: |
-          if ($env:FIREBASE_CREDENTIALS) {
-            Write-Host "FIREBASE_CREDENTIALS is defined."
-          } else {
-            Write-Host "FIREBASE_CREDENTIALS is not defined."
-          }
+      - name: Create Firebase credentials file
+        run: echo "$FIREBASE_CREDENTIALS" > $GITHUB_WORKSPACE/firebase-credentials.json
         env:
           FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
-        shell: pwsh
+
+      - name: Set Firebase credentials path
+        run: export GOOGLE_APPLICATION_CREDENTIALS="$GITHUB_WORKSPACE/firebase-credentials.json"
+        shell: bash
+
+      - name: Verify FIREBASE_CREDENTIALS
+        run: |
+          if [ -f "$GOOGLE_APPLICATION_CREDENTIALS" ]; then
+            echo "FIREBASE_CREDENTIALS is defined and file exists."
+          else
+            echo "FIREBASE_CREDENTIALS file is not defined or missing."
+            exit 1
+          fi
+        shell: bash
 
       - name: Build Electron app
         run: npm run build
         env:
-          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
+          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
 
       - name: Package Electron app for Windows
         run: |
@@ -88,7 +96,7 @@ jobs:
           npm run electron:build -- --win
         shell: pwsh
         env:
-          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
+          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
 
       - name: Upload Release Assets (Windows)
         uses: actions/upload-release-asset@v1
@@ -96,8 +104,8 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
         with:
           upload_url: ${{ needs.create_release.outputs.upload_url }}
-          asset_path: dist\associated-pension-automation-hub-1.0.159.exe
-          asset_name: associated-pension-automation-hub-1.0.159.exe
+          asset_path: dist\associated-pension-automation-hub-1.0.160.exe
+          asset_name: associated-pension-automation-hub-1.0.160.exe
           asset_content_type: application/vnd.microsoft.portale-executable
 
       - name: Upload `latest.yml` to Release Assets
@@ -109,3 +117,6 @@ jobs:
           asset_path: dist\latest.yml
           asset_name: latest.yml
           asset_content_type: application/octet-stream
+
+      - name: Clean up Firebase credentials
+        run: rm $GITHUB_WORKSPACE/firebase-credentials.json
