fix python path

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -40,7 +40,7 @@ jobs:
           node-version: '18.17.0'
 
       - name: Install dependencies
-        run: npm install
+        run: npm ci # Use ci to ensure a clean install without leftovers
 
       - name: Set up Python
         uses: actions/setup-python@v2
@@ -52,6 +52,15 @@ jobs:
 
       - name: Install Python dependencies
         run: env\Scripts\pip install -r requirements.txt
+
+      - name: Clean previous builds
+        run: |
+          if (Test-Path dist) {
+            Remove-Item -Recurse -Force dist
+          }
+          if (Test-Path release) {
+            Remove-Item -Recurse -Force release
+          }
 
       - name: Debug Python environment
         run: |
@@ -72,6 +81,16 @@ jobs:
             exit 1
           }
           npm run electron:build -- --win
+          
+          # Ensure the build was successful and output files exist
+          if (-Not (Test-Path -Path "dist" -PathType Container)) {
+            Write-Error "Build output not found!"
+            exit 1
+          }
+          if (-Not (Test-Path -Path "dist\*.exe" -PathType Leaf)) {
+            Write-Error "Installer executable not found!"
+            exit 1
+          }
 
       - name: Debug environment variables
         run: printenv
@@ -85,6 +104,6 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
         with:
           upload_url: ${{ needs.create_release.outputs.upload_url }}
-          asset_path: dist\associated-pension-automation-hub Setup 1.0.62.exe
+          asset_path: dist\associated-pension-automation-hub Setup 1.0.63.exe
           asset_name: associated-pension-automation-hub-1.0.0.exe
           asset_content_type: application/vnd.microsoft.portable-executable
