v88

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -62,29 +62,21 @@ jobs:
       - name: Install Node.js dependencies
         run: npm ci
 
-      - name: Ensure Environment Variables Point to the Correct Python Executable
+      - name: Build Electron app
+        run: npm run build
+
+      - name: Set Environment Variables for Python Executable
         run: |
           $env:PATH = "D:\a\asp-app\asp-app\env\Scripts;$env:PATH"
           $env:PYTHONHOME = "D:\a\asp-app\asp-app\env"
           $env:PYTHONPATH = "D:\a\asp-app\asp-app\env\Lib\site-packages"
           $env:PYTHONEXECUTABLE = "D:\a\asp-app\asp-app\env\Scripts\python.exe"
-          .\env\Scripts\activate
+          if (-Not (Test-Path $env:PYTHONEXECUTABLE)) {
+            Write-Error "Python executable not found at $env:PYTHONEXECUTABLE"
+            exit 1
+          }
           echo "Python Version: $(python --version)"
           echo "Python Executable: $(where python)"
-        shell: powershell
-
-      - name: Build Electron app
-        env:
-          PATH: D:\a\asp-app\asp-app\env\Scripts;${{ env.PATH }}
-          PYTHONHOME: D:\a\asp-app\asp-app\env
-          PYTHONPATH: D:\a\asp-app\asp-app\env\Lib\site-packages
-          PYTHONEXECUTABLE: D:\a\asp-app\asp-app\env\Scripts\python.exe
-          PYTHONNOUSERSITE: '1'
-        run: |
-          .\env\Scripts\activate
-          npm run build
-          echo "Post-Build Python Version: $(python --version)"
-          echo "Post-Build Python Executable: $(where python)"
         shell: powershell
 
       - name: Package Electron app for Windows
@@ -96,7 +88,6 @@ jobs:
           PYTHONNOUSERSITE: '1'
           GH_TOKEN: ${{ secrets.GH_TOKEN }}
         run: |
-          .\env\Scripts\activate
           npm run electron:build -- --win
           
           if (-Not (Test-Path -Path "dist" -PathType Container)) {
@@ -117,7 +108,7 @@ jobs:
 
       - name: Debug Environment Post-Build
         run: |
-          .\dist\associated-pension-automation-hub Setup 1.0.85.exe /S /D=D:\a\asp-app\asp-app
+          .\dist\associated-pension-automation-hub Setup 1.0.87.exe /S /D=D:\a\asp-app\asp-app
           python --version
           where python
           echo "Final PATH: $env:PATH"
@@ -132,8 +123,8 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
         with:
           upload_url: ${{ needs.create_release.outputs.upload_url }}
-          asset_path: dist\associated-pension-automation-hub Setup 1.0.87.exe
-          asset_name: associated-pension-automation-hub-1.0.87.exe
+          asset_path: dist\associated-pension-automation-hub Setup 1.0.88.exe
+          asset_name: associated-pension-automation-hub-1.0.88.exe
           asset_content_type: application/vnd.microsoft.portable-executable
 
       - name: Upload Debug Logs
